### ISSUE TITLE
Installing works on GitHub Enterprise - almost

### ISSUE THREAD

**Issue by jonbrohauge** [toolmantim/release-drafter#237]
Having followed the installations instructions, i.e. Remember to set GHE-HOST, and install via http://localhost:3000 I have succesfully(?) installed release-drafter into our GitHub Enterprise (version: 2.16.5) instance. 
I have installed the GitHub App on an test organisation and activated it in a test repository.
Having a very basic configuration of `release-drafter.yml` in the `.github` folder of the repository, there is absolutely no activity in regards to creating a release draft.
The application itself is triggered, since there is communication with https://smee.io.

A request:
![Release-Drafter-Recent-Deliveries-Request](https://user-images.githubusercontent.com/9496731/59681608-9d51f880-91d4-11e9-8b36-3227113865b7.png)

And the corresponding response:
![Release-Drafter-Recent-Deliveries-Response](https://user-images.githubusercontent.com/9496731/59681629-a773f700-91d4-11e9-9f9a-d5cd2bd29247.png)

The release-drafter config for the organization is set as such:
![Release-Drafter-GitHub-App-Config](https://user-images.githubusercontent.com/9496731/59681671-bc508a80-91d4-11e9-9fba-c4acf2cc6236.png)

The release-drafter application config is set as such:
![Release-Drafter-GitHub-App-Config-Basic-Information](https://user-images.githubusercontent.com/9496731/59681728-df7b3a00-91d4-11e9-87c7-2d5804754dbd.png)

Please advise on what further to do, so I can get this working.

We are behind a corporate proxy, but I do not think this is the issue, since there is a Response Code 200 from https://smee.io

**Comment by toolmantim** [comment]
Sorry you’re having trouble there!

I believe Smee should only be used for development, you’ll be wanting to point the GitHub App webhook settings directly to where you’re hosting the Probot app I believe?

**Comment by jonbrohauge** [comment]
@toolmantim Thanks for the clarification. Now to figure out how to host Probot on-prem... Any ideas?

**Comment by toolmantim** [comment]
https://github.com/probot/probot/issues/500#issuecomment-381266516 Seems to be the best advice.

**Comment by jonbrohauge** [comment]
Got the app working inside a docker container.
![image](https://user-images.githubusercontent.com/9496731/60508225-5121b080-9cca-11e9-8b63-7335eed94fe9.png)
I have updated the _Webhook URL_ to point to my app. Doing a PR in my repo, sends a json-payload to the app, and the app basically returns "OK" in the body. And nothing further happens.

What is expected as a response for the app to _do stuff_?
I'm trying to figure out what goes wrong where, but I'm currently stuck at everything looks green, but it does not do anything.

**Comment by toolmantim** [comment]
The Docker container log should contain a bunch of debug output that's run when the webhook is processed. Can you check that?

**Comment by jonbrohauge** [comment]
This is the output of the docker logs.
https://gist.github.com/jonbrohauge/d68af675b54e853618fab6cb66cc92ac

**Comment by jonbrohauge** [comment]
Hmmm... Tried again without any changes, and I get this:
```
2:38:17.472Z ERROR probot: Integration not found
  HttpError: Integration not found
```
https://gist.github.com/jonbrohauge/f1fc271ddaf57fa91d89bc5ff6783943

**Comment by toolmantim** [comment]
Have you created a new "app" in your GitHub Enterprise for Release Drafter, and installed it on the repos?

**Comment by jonbrohauge** [comment]
I cloned your project.
Configured the .env to use GHE_HOST. 
Added corporate proxy.
Got the app up and running on my dev machine, and had smee.io configured, as per original input in this issue.

--> Installed the app into my GHE  at this point

I took the values in the updated .env file, and loaded them into a Dockerfile.
Got the build using the Dockerfile, and spun up a container running the app.

**Comment by jonbrohauge** [comment]
I must admit that I'm not experienced with npm-stuff, and fighting a corporate proxy, thus having to host the app "in-house" is not doing me any kindness.

**Comment by jonbrohauge** [comment]
Restarted from scratch.

Got way more action in the log-file now. Now I see an error, that I could not earlier:
```
11:55:42.598Z DEBUG github: GitHub request: POST /graphql - 200 OK (installation=6)
  params: {
    "baseUrl": "https://github.domain.local/api",
    "mediaType": {
      "format": "",
      "previews": []
    },
    "request": {},
    "query": "\n  query findCommitsWithAssociatedPullRequests(\n    $name: String!\n    $owner: String!\n    $branch: String!\n    $since: GitTimestamp\n    $after: String\n  ) {\n    repository(name: $name, owner: $owner) {\n      ref(qualifiedName: $branch) {\n        target {\n          ... on Commit {\n            history(first: 100, since: $since, after: $after) {\n              totalCount\n              pageInfo {\n                hasNextPage\n                endCursor\n              }\n              nodes {\n                id\n                message\n                author {\n                  name\n                  user {\n                    login\n                  }\n                }\n                associatedPullRequests(first: 5) {\n                  nodes {\n                    title\n                    number\n                    author {\n                      login\n                    }\n                    mergedAt\n                    isCrossRepository\n                    labels(first: 10) {\n                      nodes {\n                        name\n                      }\n                    }\n                  }\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n",
    "variables": {
      "name": "probot-test-repo1",
      "owner": "probot-testing",
      "branch": "master"
    }
  }
11:55:42.599Z ERROR event: Field 'associatedPullRequests' doesn't exist on type 'Commit' (id=6ef50462-9d89-11e9-94e3-622e07411d0c)
  GraphqlError: Field 'associatedPullRequests' doesn't exist on type 'Commit'
      at request.then.response (/app/node_modules/@octokit/graphql/lib/graphql.js:31:15)
      at Object.dynatraceOnServiceExecutionIndicator (/opt/dynatrace/oneagent/agent/res/nodeagent/nodejsagent.js:1650:20)
      at Object.c.safeInvoke (/opt/dynatrace/oneagent/agent/res/nodeagent/nodejsagent.js:1701:29)
      at /opt/dynatrace/oneagent/agent/res/nodeagent/nodejsagent.js:6844:25
  --
  event: {
    "event": "push",
    "id": "6ef50462-9d89-11e9-94e3-622e07411d0c",
    "installation": 6,
    "repository": "probot-testing/probot-test-repo1"
  }
11:55:42.600Z ERROR probot: Field 'associatedPullRequests' doesn't exist on type 'Commit'
  GraphqlError: Field 'associatedPullRequests' doesn't exist on type 'Commit'
      at request.then.response (/app/node_modules/@octokit/graphql/lib/graphql.js:31:15)
      at Object.dynatraceOnServiceExecutionIndicator (/opt/dynatrace/oneagent/agent/res/nodeagent/nodejsagent.js:1650:20)
      at Object.c.safeInvoke (/opt/dynatrace/oneagent/agent/res/nodeagent/nodejsagent.js:1701:29)
      at /opt/dynatrace/oneagent/agent/res/nodeagent/nodejsagent.js:6844:25
11:55:42.601Z  INFO http: POST / 500 - 559.85 ms (id=6ef50462-9d89-11e9-94e3-622e07411d0c)
11:55:42.601Z TRACE http:  (id=6ef50462-9d89-11e9-94e3-622e07411d0c, res.duration=559.85)
  HTTP/1.1 500 Internal Server Error
  x-powered-by: Express
  x-request-id: 6ef50462-9d89-11e9-94e3-622e07411d0c
  set-cookie: dtCookie=4$61B4404D070E54FCBB7D56544A70C857; Path=/; Domain=.domain.local
```

What am I missing?
BTW. we have DynaTrace OneAgent installed on our hosts to monitor our Docker containers.

**Comment by casz** [comment]
Ask GitHub to update their enterprise edition 😆 
https://github.com/toolmantim/release-drafter/issues/234#issuecomment-501752305

**Comment by jonbrohauge** [comment]
@casz nicely spotted. Good thing I'm the GHE admin 😁 
Upgrade is on for tonight. Will comment if version [2.17.x](https://enterprise.github.com/releases/series/2.17) is good enough

**Comment by jonbrohauge** [comment]
Upgrading to GitHub Enterprise 2.17.4 makes magic happen.

**Comment by toolmantim** [comment]
Woohoo @jonbrohauge! 🎉🎉🎉

**Comment by cchanche** [comment]
For reference, should still work in v7. See #1627
