### ISSUE TITLE
Error: labels.forEach is not a function

### ISSUE THREAD

**Issue by MrZoidberg** [toolmantim/release-drafter#317]
Hey, I got a strange error during release-drafter execution:

```  Run toolmantim/release-drafter@v5.2.02s
##[error]Docker run failed with exit code 1
Run toolmantim/release-drafter@v5.2.0
/usr/bin/docker run --name *** --label *** --workdir /github/workspace --rm -e GITHUB_TOKEN -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/platform/platform":"/github/workspace" e959fb:4e4e96b1066945ebb1df2df14d41adab
13:40:19.801Z  INFO probot: ***/platform: Found 2 releases
13:40:19.802Z  INFO probot: ***/platform: Draft release: untagged-9ab21a9cb5397988cc67
13:40:19.803Z  INFO probot: ***/platform: Last release: release-1.2.35
13:40:19.803Z  INFO probot: ***/platform: Fetching all commits for branch master since 2019-10-14T17:54:37Z
13:40:20.157Z ERROR event: labels.forEach is not a function (id=d08e54e9-0e8a-4444-9c90-f32f4ad710c7)
  TypeError: labels.forEach is not a function
      at config.categories.reduce (/app/lib/releases.js:83:12)
      at Array.reduce (<anonymous>)
      at getCategoriesConfig (/app/lib/releases.js:81:46)
      at generateChangeLog (/app/lib/releases.js:129:49)
      at module.exports.generateReleaseInfo (/app/lib/releases.js:179:17)
      at app.on (/app/index.js:69:25)
  --
  event: {
    "event": "push",
    "id": "d08e54e9-0e8a-4444-9c90-f32f4ad710c7",
    "repository": "***/platform"
  }
##[error]Docker run failed with exit code 1```

**Comment by hugo-vrijswijk** [comment]
I just had the same issue and fixed it. The problem was that I had a category without a `label` or `labels` attached to it. Thinking it would get added to a 'default' category. I removed the category without labels and it worked perfectly. [See here for what I did](https://github.com/stryker-mutator/stryker4s/commit/666269a4db60bc8ad46031281cdb2209cc3f958b)

**Comment by MrZoidberg** [comment]
thanks!
