### ISSUE TITLE
Cannot read property 'title' of undefined for PRs created by Dependabot

### ISSUE THREAD

**Issue by TondaHack** [toolmantim/release-drafter#320]
## Description: 
When we the PR is created by Dependabot (https://dependabot.com/), action fails on  `Cannot read property 'title' of undefined `

```
Run toolmantim/release-drafter@v5.2.0
/usr/bin/docker run --name d1dd0209cee43440ea2c4bc5e4580b073_8a0a67 --label 10865d --workdir /github/workspace --rm -e GITHUB_TOKEN -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/repo/repo":"/github/workspace" 10865d:1dd0209cee43440ea2c4bc5e4580b073
09:26:23.226Z  INFO probot: org/repo: Found 3 releases
09:26:23.228Z  INFO probot: org/repo: Draft release: untagged-40b38943eb73f6e840c3
09:26:23.228Z  INFO probot: org/repo: Last release: v0.0.2
09:26:23.229Z  INFO probot: org/repo: Fetching all commits for branch master since 2019-10-11T15:13:37Z
09:26:23.870Z ERROR event: Cannot read property 'title' of undefined (id=bd097ac6-6377-45b4-a640-acca61cbb39c)
  TypeError: Cannot read property 'title' of undefined
      at orderedCategories.reduce (/app/lib/releases.js:144:51)
      at Array.reduce (<anonymous>)
      at generateChangeLog (/app/lib/releases.js:136:6)
      at module.exports.generateReleaseInfo (/app/lib/releases.js:179:17)
      at app.on (/app/index.js:69:25)
  --
  event: {
    "event": "push",
    "id": "bd097ac6-6377-45b4-a640-acca61cbb39c",
    "repository": "org/repo"
  }
##[error]Docker run failed with exit code 1
```

## Steps to reproduce
1. Configure release drafter (It worked)
2. Configure Dependabot
3. When Dependabot creates PR with an update of some dependency, merge it
4. Release Drafter fails

## PR example of Dependabot:
![Screenshot 2019-11-07 at 10 00 24](https://user-images.githubusercontent.com/8971082/68379868-9fe2c980-0146-11ea-8f9c-507063fd229e.png)

**Comment by TondaHack** [comment]
The issue was on my side. `release-drafter.yml` -> categories -> label(s). 
```
categories:
  - title: '🧰 Maintenance'
    label:
      - 'chore'
      - 'dependencies'
```
`label` instead of `labels`. The script created `chore,dependencies` property. `configCategories["chore,dependencies"]` didn't exist.
