### ISSUE TITLE
Empty value for parameter `id`: undefined

### ISSUE THREAD

**Issue by frenck** [toolmantim/release-drafter#47]
I'm experiencing the follow issue:

```text
11:05:22.661Z DEBUG github: GitHub request: GET /repos/:owner/:repo/compare/:base...:head - 200 OK (id=191aa04e-a07b-11e8-848e-10235e0ffbd8, installation=152769)
  params: {
    "owner": "frenck",
    "repo": "addon-example",
    "base": "v10.32.6",
    "head": "master",
    "baseUrl": "https://api.github.com",
    "request": {
      "timeout": 0
    }
  }
11:05:22.662Z  INFO probot: frenck/frenck: Found pull request numbers: 6
11:05:23.620Z DEBUG github: GitHub request: GET /repos/:owner/:repo/pulls/:number - 200 OK (id=191aa04e-a07b-11e8-848e-10235e0ffbd8, installation=152769)
  params: {
    "owner": "frenck",
    "repo": "addon-example",
    "number": 6,
    "baseUrl": "https://api.github.com",
    "request": {
      "timeout": 0
    }
  }
11:05:23.620Z  INFO probot: frenck/frenck: Updating existing draft release
11:05:23.620Z ERROR event: Empty value for parameter 'id': undefined (id=191aa04e-a07b-11e8-848e-10235e0ffbd8)
  HttpError: Empty value for parameter 'id': undefined
      at Object.keys.forEach.parameterName (/Volumes/CODE/hassio-addons/probot-addons-assistant/node_modules/probot/node_modules/@octokit/rest/lib/plugins/endpoint-methods/validate.js:27:13)
      at Array.forEach (<anonymous>)
      at validate (/Volumes/CODE/hassio-addons/probot-addons-assistant/node_modules/probot/node_modules/@octokit/rest/lib/plugins/endpoint-methods/validate.js:9:31)
      at process._tickCallback (internal/process/next_tick.js:68:7)
  --
  event: {
    "id": "191aa04e-a07b-11e8-848e-10235e0ffbd8",
    "event": "push",
    "repository": "frenck/addon-example",
    "installation": 152769
  }
```

Any idea?

**Comment by toolmantim** [comment]
Thanks for that. Is there an old draft release in the repository by any chance? Strange that the `draftRelease.tag_name` returned null

**Comment by frenck** [comment]
Nope, only the one created by this code.

**Comment by toolmantim** [comment]
Could you change https://github.com/toolmantim/release-drafter/blob/master/lib/releases.js#L30 to log the full draftRelease object, and not just the tag name, and see what it outputs for me?
